[package]
edition = "2021"
name = "call_graphic_lib"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18"
lens = {path = "../../lens"}

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
